function jpstc_template()
%JPSTC_TEMPLATE   Draw template to present JPSTC data

close all

%global declarations
global H2Figure H2Info H2Titlebar
global H2Jpsth H2Colorbar H2HistX H2HistY H2Corr H2Coin H2Corr_2
global DefScaleSize
DefScaleSize=1;
DefFontSize=4;
DefFontName='Arial';
DefAxesLineWidth=0.05;

%color defs
colGray=[0.2 0.2 0.2];

%get Screen defs
set(0,'units','pixels');
set(0,'defaulttextfontsize',DefFontSize*DefScaleSize,...
    'defaulttextfontname', DefFontName,...
    'defaultaxeslinewidth',DefAxesLineWidth);

%get Screen Resolution
% ScreenSize = get(0,'screensize');
% sWIDTH = ScreenSize(3);
% sHEIGHT = ScreenSize(4);

wWIDTH = 1050;
wHEIGHT = 800;
yaspect=5/4;
offset=1/(11*16);% 1/16"
PM=4*offset; %set page margin to 1/4"

%Draw Main Figure
H2Figure = figure('position',[50 100 wWIDTH wHEIGHT],...
                    'paperposition',[PM PM, 1-2*PM, 1-2*PM],...
                    'units','normalized',...
                    'paperunits','normalized',...
                    'color',[1 1 1],...
                    'numbertitle','off',...
                    'renderer','painters',...
                    'renderermode','manual',...
                    'menubar','none',...
                    'Resize','off',...
                    'name',' JPSTH FIGURE ',...
                    'tag','H2Figure');
orient landscape;

%Draw Border
axes('parent',H2Figure,...
       'position',[offset offset 1-2*offset 1-2*offset],...
       'box','on',...
       'tag','H2OutLine',...
       'xcolor',[0 0 0], 'ycolor',[0 0 0],...
       'xtick',[], 'ytick',[]);


% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %


Gap1=8;% 1/2"
Gap2=5;
PlotGap1=1;
PlotGap2=0.5;
HistH=8;
JpsthSize=36;
ColorbarH=2;
VGap1=3;
PlotH=(18-VGap1)/1.5;%16;%15
%Ylocs
TotHyt=8.5*16;
fromTop=22;

%Draw Info box
PlotPos = [2 160 115 12].*offset;
H2Titlebar = axes('parent',H2Figure,...
                    'position',PlotPos,...
                    'box','on',...
                    'layer','top',...
                    'tag','H2Titlebar',...
                    'xtick',[],'ytick',[],...
                    'xcolor',colGray,'ycolor',colGray);

%plot the axes for the plots/images
for ii=1:5
    if ii<4
    NextLeft=(Gap1+HistH+PlotGap1+JpsthSize+PlotGap2+ColorbarH+Gap2-1)*(ii-1);
    end;

    switch ii
        case {1, 2}
            InfoPos = [NextLeft+Gap1+HistH+PlotGap1...
                        (TotHyt-fromTop+PlotGap1)*yaspect...
                        JpsthSize...
                        HistH*yaspect];
            H2Info(ii) = axes('parent',H2Figure,...
                                'position',InfoPos.*offset,...
                                'box','on',...
                                'layer','top',...
                                'xtick',[],'ytick',[],...
                                'xcolor',colGray,'ycolor',colGray);

            HistYPos = [NextLeft+Gap1...
                        (TotHyt-fromTop-JpsthSize)*yaspect...
                        HistH...
                        JpsthSize*yaspect];
            H2HistY(ii) = axes('parent',H2Figure,...
                                'position',HistYPos.*offset,...
                                'box','on',...
                                'layer','top',...
                                'xtick',[],'ytick',[],...
                                'xcolor',colGray,'ycolor',colGray,...
                                'cameraupvector',[1 0 0],...
                                'tag',['H2HistY(',num2str(ii),')']);

            JpsthPos = [NextLeft+Gap1+HistH+PlotGap1...
                        (TotHyt-fromTop-JpsthSize)*yaspect...
                        JpsthSize...
                        JpsthSize*yaspect];
            H2Jpsth(ii) = axes('parent',H2Figure,...
                                'position',JpsthPos.*offset,...
                                'box','on',...
                                'xtick',[],'ytick',[],...
                                'xcolor',colGray,'ycolor',colGray,...
                                'tag',['H2Jpsth(',num2str(ii),')']);

            ColorbarPos = [NextLeft+Gap1+HistH+PlotGap1+JpsthSize+PlotGap1...
                            (TotHyt-fromTop-JpsthSize)*yaspect...
                            ColorbarH...
                            JpsthSize*yaspect];
            H2Colorbar(ii) = axes('parent',H2Figure,...
                                    'position',ColorbarPos.*offset,...
                                    'box','on',...
                                    'xtick',[],'ytick',[],...
                                    'xcolor',colGray,'ycolor',colGray,...
                                    'tag',['H2Colorbar(',num2str(ii),')']);

            HistXPos = [NextLeft+Gap1+HistH+PlotGap1...
                        (TotHyt-fromTop-JpsthSize-PlotGap1-HistH)*yaspect...
                        JpsthSize...
                        HistH*yaspect];
            H2HistX(ii) = axes('parent',H2Figure,...
                                'position',HistXPos.*offset,...
                                'box','on',...
                                'layer','top',...
                                'xtick',[],'ytick',[],...
                                'xcolor',colGray,'ycolor',colGray,...
                                'tag',['H2HistX(',num2str(ii),')']);

            HOffset1 = ((Gap1+HistH+PlotGap1)*ii)...
                        + ((JpsthSize+PlotGap2+ColorbarH+Gap2-1)*(ii-1));
            NP=3;
            for jj=1:NP

                NextBottom = TotHyt-fromTop-JpsthSize-PlotGap1-HistH-VGap1-(PlotH*jj)-(VGap1*(jj-1));

                PlotPos = [HOffset1...
                            NextBottom*yaspect...
                            JpsthSize...
                            PlotH*yaspect];
                Temp = axes('parent',H2Figure,...
                            'position',PlotPos.*offset,...
                            'box','on',...
                            'layer','top',...
                            'xtick',[],'ytick',[],...
                            'xcolor',colGray,'ycolor',colGray);

                switch jj
                    case 1
                        H2Corr(ii)=Temp;
                        set(Temp,'tag',['H2Corr(',num2str(ii),')']);
                    case 2
                        H2Coin(ii)=Temp;
                        set(Temp,'tag',['H2Coin(',num2str(ii),')']);
                        % added 012506 for smaller sorr -20 +20 ms
                    case 3
                        H2Corr_2(ii)=Temp;
                        set(Temp,'tag',['H2Corr_2(',num2str(ii),')']);

                end
                drawnow
            end


        case 3
            JpsthPos = [NextLeft+HistH+PlotGap1...
                        (TotHyt-2*JpsthSize-2*Gap2)*yaspect...
                        JpsthSize...
                        JpsthSize*yaspect];
            H2Jpsth(ii)=axes('parent',H2Figure,...
                                'position',JpsthPos.*offset,...
                                'box','on',...
                                'xtick',[],'ytick',[],...
                                'xcolor',colGray,'ycolor',colGray,...
                                'tag',['H2Jpsth(',num2str(ii),')']);

        case 4
            JpsthPos = [NextLeft+HistH+PlotGap1...
                        (TotHyt-3*JpsthSize-4*Gap2)*yaspect...
                        JpsthSize...
                        JpsthSize*yaspect];
            H2Jpsth(ii)=axes('parent',H2Figure,...
                                'position',JpsthPos.*offset,...
                                'box','on',...
                                'xtick',[],'ytick',[],...
                                'xcolor',colGray,'ycolor',colGray,...
                                'tag',['H2Jpsth(',num2str(ii),')']);


            ColorbarPos = [NextLeft+HistH+2*PlotGap1+JpsthSize...
                            (TotHyt-3*JpsthSize-4*Gap2)*yaspect...
                            ColorbarH...
                            JpsthSize*yaspect];
            H2Colorbar(ii) = axes('parent',H2Figure,...
                                    'position',ColorbarPos.*offset,...
                                    'box','on',...
                                    'xtick',[],'ytick',[],...
                                    'xcolor',colGray,'ycolor',colGray,...
                                    'tag',['H2Colorbar(',num2str(ii),')']);
        case 5
            JpsthPos = [NextLeft+HistH+PlotGap1...
                        (TotHyt-JpsthSize)*yaspect...
                        JpsthSize...
                        JpsthSize*yaspect];
            H2Jpsth(ii)=axes('parent',H2Figure,...
                                'position',JpsthPos.*offset,...
                                'box','on',...
                                'xtick',[],'ytick',[],...
                                'xcolor',colGray,'ycolor',colGray,...
                                'tag',['H2Jpsth(',num2str(ii),')']);
    end

end

