integrated_in.slow_correct_missed_dead = missed_integrated_in.slow_correct_missed_dead;
integrated_in.slow_correct_missed_dead_binFast = missed_integrated_in.slow_correct_missed_dead_binFast;
integrated_in.slow_correct_missed_dead_binMed = missed_integrated_in.slow_correct_missed_dead_binMed;
integrated_in.slow_correct_missed_dead_binSlow = missed_integrated_in.slow_correct_missed_dead_binSlow;
integrated_in.slow_errors_missed_dead = missed_integrated_in.slow_errors_missed_dead;
integrated_in.slow_errors_missed_dead_binFast = missed_integrated_in.slow_errors_missed_dead_binFast;
integrated_in.slow_errors_missed_dead_binMed = missed_integrated_in.slow_errors_missed_dead_binMed;
integrated_in.slow_errors_missed_dead_binSlow = missed_integrated_in.slow_errors_missed_dead_binSlow;


integrated_in.fast_correct_missed_dead = missed_integrated_in.fast_correct_missed_dead;
integrated_in.fast_correct_missed_dead_binFast = missed_integrated_in.fast_correct_missed_dead_binFast;
integrated_in.fast_correct_missed_dead_binMed = missed_integrated_in.fast_correct_missed_dead_binMed;
integrated_in.fast_correct_missed_dead_binSlow = missed_integrated_in.fast_correct_missed_dead_binSlow;
integrated_in.fast_errors_missed_dead = missed_integrated_in.fast_errors_missed_dead;
integrated_in.fast_errors_missed_dead_binFast = missed_integrated_in.fast_errors_missed_dead_binFast;
integrated_in.fast_errors_missed_dead_binMed = missed_integrated_in.fast_errors_missed_dead_binMed;
integrated_in.fast_errors_missed_dead_binSlow = missed_integrated_in.fast_errors_missed_dead_binSlow;

clear missed_integrated_in

integrated_out.slow_correct_missed_dead = missed_integrated_out.slow_correct_missed_dead;
integrated_out.slow_correct_missed_dead_binFast = missed_integrated_out.slow_correct_missed_dead_binFast;
integrated_out.slow_correct_missed_dead_binMed = missed_integrated_out.slow_correct_missed_dead_binMed;
integrated_out.slow_correct_missed_dead_binSlow = missed_integrated_out.slow_correct_missed_dead_binSlow;
integrated_out.slow_errors_missed_dead = missed_integrated_out.slow_errors_missed_dead;
integrated_out.slow_errors_missed_dead_binFast = missed_integrated_out.slow_errors_missed_dead_binFast;
integrated_out.slow_errors_missed_dead_binMed = missed_integrated_out.slow_errors_missed_dead_binMed;
integrated_out.slow_errors_missed_dead_binSlow = missed_integrated_out.slow_errors_missed_dead_binSlow;
 

integrated_out.fast_correct_missed_dead = missed_integrated_out.fast_correct_missed_dead;
integrated_out.fast_correct_missed_dead_binFast = missed_integrated_out.fast_correct_missed_dead_binFast;
integrated_out.fast_correct_missed_dead_binMed = missed_integrated_out.fast_correct_missed_dead_binMed;
integrated_out.fast_correct_missed_dead_binSlow = missed_integrated_out.fast_correct_missed_dead_binSlow;
integrated_out.fast_errors_missed_dead = missed_integrated_out.fast_errors_missed_dead;
integrated_out.fast_errors_missed_dead_binFast = missed_integrated_out.fast_errors_missed_dead_binFast;
integrated_out.fast_errors_missed_dead_binMed = missed_integrated_out.fast_errors_missed_dead_binMed;
integrated_out.fast_errors_missed_dead_binSlow = missed_integrated_out.fast_errors_missed_dead_binSlow;

clear missed_integrated_out


integrated_diff.slow_correct_missed_dead = missed_integrated_diff.slow_correct_missed_dead;
integrated_diff.slow_correct_missed_dead_binFast = missed_integrated_diff.slow_correct_missed_dead_binFast;
integrated_diff.slow_correct_missed_dead_binMed = missed_integrated_diff.slow_correct_missed_dead_binMed;
integrated_diff.slow_correct_missed_dead_binSlow = missed_integrated_diff.slow_correct_missed_dead_binSlow;
integrated_diff.slow_errors_missed_dead = missed_integrated_diff.slow_errors_missed_dead;
integrated_diff.slow_errors_missed_dead_binFast = missed_integrated_diff.slow_errors_missed_dead_binFast;
integrated_diff.slow_errors_missed_dead_binMed = missed_integrated_diff.slow_errors_missed_dead_binMed;
integrated_diff.slow_errors_missed_dead_binSlow = missed_integrated_diff.slow_errors_missed_dead_binSlow;


integrated_diff.fast_correct_missed_dead = missed_integrated_diff.fast_correct_missed_dead;
integrated_diff.fast_correct_missed_dead_binFast = missed_integrated_diff.fast_correct_missed_dead_binFast;
integrated_diff.fast_correct_missed_dead_binMed = missed_integrated_diff.fast_correct_missed_dead_binMed;
integrated_diff.fast_correct_missed_dead_binSlow = missed_integrated_diff.fast_correct_missed_dead_binSlow;
integrated_diff.fast_errors_missed_dead = missed_integrated_diff.fast_errors_missed_dead;
integrated_diff.fast_errors_missed_dead_binFast = missed_integrated_diff.fast_errors_missed_dead_binFast;
integrated_diff.fast_errors_missed_dead_binMed = missed_integrated_diff.fast_errors_missed_dead_binMed;
integrated_diff.fast_errors_missed_dead_binSlow = missed_integrated_diff.fast_errors_missed_dead_binSlow;


 
clear missed_integrated_diff 

leaky_integrated_in.slow_correct_missed_dead = missed_leaky_integrated_in.slow_correct_missed_dead;
leaky_integrated_in.slow_correct_missed_dead_binFast = missed_leaky_integrated_in.slow_correct_missed_dead_binFast;
leaky_integrated_in.slow_correct_missed_dead_binMed = missed_leaky_integrated_in.slow_correct_missed_dead_binMed;
leaky_integrated_in.slow_correct_missed_dead_binSlow = missed_leaky_integrated_in.slow_correct_missed_dead_binSlow;
leaky_integrated_in.slow_errors_missed_dead = missed_leaky_integrated_in.slow_errors_missed_dead;
leaky_integrated_in.slow_errors_missed_dead_binFast = missed_leaky_integrated_in.slow_errors_missed_dead_binFast;
leaky_integrated_in.slow_errors_missed_dead_binMed = missed_leaky_integrated_in.slow_errors_missed_dead_binMed;
leaky_integrated_in.slow_errors_missed_dead_binSlow = missed_leaky_integrated_in.slow_errors_missed_dead_binSlow;
 
 
leaky_integrated_in.fast_correct_missed_dead = missed_leaky_integrated_in.fast_correct_missed_dead;
leaky_integrated_in.fast_correct_missed_dead_binFast = missed_leaky_integrated_in.fast_correct_missed_dead_binFast;
leaky_integrated_in.fast_correct_missed_dead_binMed = missed_leaky_integrated_in.fast_correct_missed_dead_binMed;
leaky_integrated_in.fast_correct_missed_dead_binSlow = missed_leaky_integrated_in.fast_correct_missed_dead_binSlow;
leaky_integrated_in.fast_errors_missed_dead = missed_leaky_integrated_in.fast_errors_missed_dead;
leaky_integrated_in.fast_errors_missed_dead_binFast = missed_leaky_integrated_in.fast_errors_missed_dead_binFast;
leaky_integrated_in.fast_errors_missed_dead_binMed = missed_leaky_integrated_in.fast_errors_missed_dead_binMed;
leaky_integrated_in.fast_errors_missed_dead_binSlow = missed_leaky_integrated_in.fast_errors_missed_dead_binSlow;
 

 
clear missed_leaky_integrated_in


leaky_integrated_out.slow_correct_missed_dead = missed_leaky_integrated_out.slow_correct_missed_dead;
leaky_integrated_out.slow_correct_missed_dead_binFast = missed_leaky_integrated_out.slow_correct_missed_dead_binFast;
leaky_integrated_out.slow_correct_missed_dead_binMed = missed_leaky_integrated_out.slow_correct_missed_dead_binMed;
leaky_integrated_out.slow_correct_missed_dead_binSlow = missed_leaky_integrated_out.slow_correct_missed_dead_binSlow;
leaky_integrated_out.slow_errors_missed_dead = missed_leaky_integrated_out.slow_errors_missed_dead;
leaky_integrated_out.slow_errors_missed_dead_binFast = missed_leaky_integrated_out.slow_errors_missed_dead_binFast;
leaky_integrated_out.slow_errors_missed_dead_binMed = missed_leaky_integrated_out.slow_errors_missed_dead_binMed;
leaky_integrated_out.slow_errors_missed_dead_binSlow = missed_leaky_integrated_out.slow_errors_missed_dead_binSlow;
 
 
leaky_integrated_out.fast_correct_missed_dead = missed_leaky_integrated_out.fast_correct_missed_dead;
leaky_integrated_out.fast_correct_missed_dead_binFast = missed_leaky_integrated_out.fast_correct_missed_dead_binFast;
leaky_integrated_out.fast_correct_missed_dead_binMed = missed_leaky_integrated_out.fast_correct_missed_dead_binMed;
leaky_integrated_out.fast_correct_missed_dead_binSlow = missed_leaky_integrated_out.fast_correct_missed_dead_binSlow;
leaky_integrated_out.fast_errors_missed_dead = missed_leaky_integrated_out.fast_errors_missed_dead;
leaky_integrated_out.fast_errors_missed_dead_binFast = missed_leaky_integrated_out.fast_errors_missed_dead_binFast;
leaky_integrated_out.fast_errors_missed_dead_binMed = missed_leaky_integrated_out.fast_errors_missed_dead_binMed;
leaky_integrated_out.fast_errors_missed_dead_binSlow = missed_leaky_integrated_out.fast_errors_missed_dead_binSlow;
 
clear missed_leaky_integrated_out

leaky_integrated_diff.slow_correct_missed_dead = missed_leaky_integrated_diff.slow_correct_missed_dead;
leaky_integrated_diff.slow_correct_missed_dead_binFast = missed_leaky_integrated_diff.slow_correct_missed_dead_binFast;
leaky_integrated_diff.slow_correct_missed_dead_binMed = missed_leaky_integrated_diff.slow_correct_missed_dead_binMed;
leaky_integrated_diff.slow_correct_missed_dead_binSlow = missed_leaky_integrated_diff.slow_correct_missed_dead_binSlow;
leaky_integrated_diff.slow_errors_missed_dead = missed_leaky_integrated_diff.slow_errors_missed_dead;
leaky_integrated_diff.slow_errors_missed_dead_binFast = missed_leaky_integrated_diff.slow_errors_missed_dead_binFast;
leaky_integrated_diff.slow_errors_missed_dead_binMed = missed_leaky_integrated_diff.slow_errors_missed_dead_binMed;
leaky_integrated_diff.slow_errors_missed_dead_binSlow = missed_leaky_integrated_diff.slow_errors_missed_dead_binSlow;
 
 
leaky_integrated_diff.fast_correct_missed_dead = missed_leaky_integrated_diff.fast_correct_missed_dead;
leaky_integrated_diff.fast_correct_missed_dead_binFast = missed_leaky_integrated_diff.fast_correct_missed_dead_binFast;
leaky_integrated_diff.fast_correct_missed_dead_binMed = missed_leaky_integrated_diff.fast_correct_missed_dead_binMed;
leaky_integrated_diff.fast_correct_missed_dead_binSlow = missed_leaky_integrated_diff.fast_correct_missed_dead_binSlow;
leaky_integrated_diff.fast_errors_missed_dead = missed_leaky_integrated_diff.fast_errors_missed_dead;
leaky_integrated_diff.fast_errors_missed_dead_binFast = missed_leaky_integrated_diff.fast_errors_missed_dead_binFast;
leaky_integrated_diff.fast_errors_missed_dead_binMed = missed_leaky_integrated_diff.fast_errors_missed_dead_binMed;
leaky_integrated_diff.fast_errors_missed_dead_binSlow = missed_leaky_integrated_diff.fast_errors_missed_dead_binSlow;

clear missed_leaky_integrated_diff