% Ex-gaussian random numbers can be generated by adding together random numbers from a normal distribution
% and an exponential distribution (see Ratcliff 1979 Psych Bull p. 451).
%
% RPH

function data = exgaussrnd(u_norm,sigma_norm,u_exp,size1,size2)

if nargin < 4
    size1 = 1;
    size2 = 1;
end

norm_component = normrnd(u_norm,sigma_norm,size1,size2);
exp_component = exprnd(u_exp,size1,size2);

data = norm_component + exp_component;

end