function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1,YDATA1,ZDATA1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 08-Nov-2010 13:00:49

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'Layer','top',...
    'FontWeight','bold',...
    'FontSize',14);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-100 500]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 100.5859375]);
hold(axes1,'all');
xlim([-100 500])
ylim([0 100])

% Create contour
contour(xdata1,ydata1,zdata1,'LineColor',[0 0 0],'Fill','on','Parent',axes1);

% Create colorbar
colorbar('peer',axes1,'LineWidth',2,'FontWeight','bold','FontSize',14);

